### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by cpjolicoeur**
Fix some spelling

### CODE REVIEW

**Comment by Deraen** [comment]
While `keywordize` might not be completely valid spelling, it is used in Clojure ecosystem: https://clojuredocs.org/clojure.walk/keywordize-keys

**Comment by cpjolicoeur** [comment]
sure, the real misspelling was "keywodize" (no r) instead of "keywordize".  No hyphen is fine.

**Comment by cpjolicoeur** [comment]
gah, you are too quick for me.  I was going to squash these commits down into 1.

**Comment by Deraen** [comment]
And I already changed this myself but then also merged this. Whatever :D

**Comment by cpjolicoeur** [comment]
:+1: thanks

**Pull request merged**
