### PR TITLE
Pass a nil body through unchanged

### PR DESCRIPTION
**Pull request by hlship**
As per issue https://github.com/ngrunwald/ring-middleware-format/issues/39, a nil body is converted to "null" (for JSON) or "nil" (for EDN). This patch recognizes that situation and effectively leaves the body as nil, but updates the content-type and content-length headers.

### CODE REVIEW

**Comment by joelittlejohn** [comment]
Good stuff. It may be worth squashing these commits before they make it into the upstream log.

**Comment by joelittlejohn** [comment]
Ah, looks like this has already been tackled in #28 (Sept 2014).

**Comment by minimal** [comment]
I would use this fork where it is already fixed https://github.com/metosin/ring-middleware-format
see #36

**Comment by ngrunwald** [comment]
Thanks, squashed and merged!

**Pull request closed without merging**
