### PR TITLE
Bumping versions for everything, including Clojure 1.8.

### PR DESCRIPTION
**Pull request by cgore**

### CODE REVIEW

**Comment by cgore** [comment]
Hmm.  That error with openjdk6 and openjdk7 is interesting.
I've only got Oracle Java on my macbook though.

**Comment by Deraen** [comment]
I fixed the Cheshire problem upstream: https://github.com/dakrone/cheshire/pull/101

**Comment by cgore** [comment]
Cool.

**Comment by Deraen** [comment]
Clojure 1.8 is already used by dev profile, it is unnecessary to add another profile.

**Comment by Deraen** [comment]
Diff looks good now.

Lastly, could you squash the commits into one? (`git rebase -i  HEAD~4` and select s or squash for the last three lines).

Related,
@ngrunwald Could you check the repository settings and enable "Squash merge" support: https://github.com/blog/2141-squash-your-commits or give me admin right.

**Pull request merged**
